/* Service Worker : cache-first. Incrémenter VERSION à chaque mise à jour. L'audio complet est géré par SongStore (Cache Storage). */
const VERSION='jieebeat-v7';
const ASSETS=["./", "index.html", "manifest.webmanifest", "css/style.css", "icons/icon-192.png", "icons/icon-512.png", "i18n/fr.json", "i18n/en.json", "data/challenges.json", "data/collection.json", "data/achievements.json", "songs/index.json", "js/config.js", "js/i18n.js", "js/store.js", "js/songstore.js", "js/songs.js", "js/audio.js", "js/engine.js", "js/daily.js", "js/achievements.js", "js/collection.js", "js/bg.js", "js/ui.js", "js/nav.js", "js/main.js", "songs/pina-colada/chart.json", "songs/pina-colada/cover.webp", "songs/pina-colada/preview.m4a", "songs/c-est-glace/chart.json", "songs/c-est-glace/cover.webp", "songs/c-est-glace/preview.m4a", "songs/my-g/chart.json", "songs/my-g/cover.webp", "songs/my-g/preview.m4a", "songs/dans-toutes-les-langues/chart.json", "songs/dans-toutes-les-langues/cover.webp", "songs/dans-toutes-les-langues/preview.m4a", "songs/les-choses-de-l-amour/chart.json", "songs/les-choses-de-l-amour/cover.webp", "songs/les-choses-de-l-amour/preview.m4a", "songs/jamais-a-coup-de-pied/chart.json", "songs/jamais-a-coup-de-pied/cover.webp", "songs/jamais-a-coup-de-pied/preview.m4a", "songs/stranger/chart.json", "songs/stranger/cover.webp", "songs/stranger/preview.m4a", "songs/l-argent-appelle-l-argent/chart.json", "songs/l-argent-appelle-l-argent/cover.webp", "songs/l-argent-appelle-l-argent/preview.m4a", "songs/coffin-dance/chart.json", "songs/coffin-dance/cover.webp", "songs/coffin-dance/preview.m4a", "songs/azo-n-kplon/chart.json", "songs/azo-n-kplon/cover.webp", "songs/azo-n-kplon/preview.m4a", "songs/deodorant/chart.json", "songs/deodorant/cover.webp", "songs/deodorant/preview.m4a", "songs/papaoutai/chart.json", "songs/papaoutai/cover.webp", "songs/papaoutai/preview.m4a", "songs/gbokirigbo/chart.json", "songs/gbokirigbo/cover.webp", "songs/gbokirigbo/preview.m4a", "songs/che-che-kule/chart.json", "songs/che-che-kule/cover.webp", "songs/che-che-kule/preview.m4a", "songs/stuck-on-you/chart.json", "songs/stuck-on-you/cover.webp", "songs/stuck-on-you/preview.m4a", "songs/ye-mama/chart.json", "songs/ye-mama/cover.webp", "songs/ye-mama/preview.m4a", "songs/je-t-attendrai/chart.json", "songs/je-t-attendrai/cover.webp", "songs/je-t-attendrai/preview.m4a", "songs/gogohoun/chart.json", "songs/gogohoun/cover.webp", "songs/gogohoun/preview.m4a", "songs/ozeba/chart.json", "songs/ozeba/cover.webp", "songs/ozeba/preview.m4a", "songs/mamaloko/chart.json", "songs/mamaloko/cover.webp", "songs/mamaloko/preview.m4a", "songs/il-va-donner-pour-moi/chart.json", "songs/il-va-donner-pour-moi/cover.webp", "songs/il-va-donner-pour-moi/preview.m4a"];
self.addEventListener('install',e=>e.waitUntil(caches.open(VERSION).then(c=>Promise.all(ASSETS.map(u=>c.add(u).catch(()=>{})))).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(k=>Promise.all(k.filter(x=>x.startsWith('jieebeat-v')&&x!==VERSION).map(x=>caches.delete(x)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',e=>{
 if(e.request.method!=='GET')return;
 const big=/\.m4a$/.test(new URL(e.request.url).pathname);
 e.respondWith(caches.match(e.request,{ignoreSearch:true}).then(hit=>hit||fetch(e.request).then(r=>{if(r.ok&&!big){const cp=r.clone();caches.open(VERSION).then(c=>c.put(e.request,cp))}return r}).catch(()=>caches.match('index.html'))));
});
